### ISSUE TITLE
Chrome says manifest is outdated

### ISSUE THREAD

**Issue by Cornelius-Figgle** [anzemur/ad-meme#1]
![image](https://user-images.githubusercontent.com/110970234/217897930-98b1d636-9711-444e-b51c-ef4021db3ddc.png)

https://developer.chrome.com/blog/mv2-transition

I did also try just changing the version number to 3, then threw more errors...

Can I also ask, do I need to be running a AWS instance and have npm installed, or can I just upload the extension to my chrome? Thanks

**Comment by anzemur** [comment]
The error that you got is a warning and I think that this shouldn't be a problem for now. Yes, you need to create your own AWS S3 bucket instance for image file storage and run your instance of our API with Node.js (npm). 

We currently don't provide any live instances of the application.

**Comment by Cornelius-Figgle** [comment]
> The error that you got is a warning and I think that this shouldn't be a problem for now

Okay, thanks!

> We currently don't provide any live instances of the application

Awww - I don't really want to have to setup accounts for all of this, so will leave the project in stars list for now. Thanks for the (insanely) quick response!
